### ISSUE TITLE
Gói gọn chương trình này sẽ gọn gàng hơn đó bạn.

### ISSUE THREAD

**Issue by storytellar** [TranCuongQ4/TuTaoX-UI#1]
Bạn nên Dockerize nó, biến nó thành 1 container của Docker chạy riêng biệt để cho dễ quản lý ở trên VPS và tránh xung đột giữa nhiều thứ cần chạy trên VPS.
Trân trọng.

**Comment by pipizune** [comment]
có thể cho mình biết học mấy cái này từ đâu ko mình cần học tập tý
